version: "3.5"
services:
  sopds:
    build: .
    container_name: sopds
    image: edv64/sopds
    restart: unless-stopped
    environment:
      - DB_USER
      - DB_NAME
      - DB_PASS
      - DB_HOST
      - PORT
    ports:
      - $PORT:$PORT
    volumes:
      - $LIBRARY_PATH:/books:ro
      - /var/log/sopds:/usr/src/sopds/opds_catalog/log
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sopds-rt.entrypoints=https-ep"
      - "traefik.http.routers.sopds-rt.rule=Host(`$HOSTNAME`)"
      - "traefik.http.routers.sopds-rt.tls=true"
#      - "traefik.http.routers.sopds-router.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.sopds-rt.service=sopds-service"
      - "traefik.http.routers.sopds-rt.middlewares=geoblock-RU-mw@file"
      - "traefik.http.services.sopds-service.loadbalancer.server.port=$PORT"
    network_mode: bridge
#networks:
#  default:
#    name: traefik_subnet
#    external: true
